# Generated by Django 6.1.1 on 2026-09-11 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='fav_dish',
            new_name='dish',
        ),
    ]
